//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace swViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("swViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!-- Diff which was parsed from mediawiki begins here --&gt;
        ///&lt;table class=&apos;diff diff-contentalign-left&apos;&gt;
        ///&lt;colgroup&gt;&lt;col class=&apos;diff-marker&apos;&gt;
        ///        &lt;col class=&apos;diff-content&apos;&gt;
        ///        &lt;col class=&apos;diff-marker&apos;&gt;
        ///        &lt;col class=&apos;diff-content&apos;&gt;
        ///&lt;/colgroup&gt;&quot;
        ///&lt;/table&gt;
        ///  &lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string diffEnd {
            get {
                return ResourceManager.GetString("diffEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        /// &lt;head&gt;
        ///    &lt;meta http-equiv=&apos;Content-Type&apos; content=&apos;text/html;charset=UTF-8&apos;&gt;
        ///    &lt;style type=&apos;text/css&apos;&gt;
        ///    /* Copied from https://git.wikimedia.org/blob/mediawiki%2Fcore.git/HEAD/resources%2Fmediawiki.action%2Fmediawiki.action.history.diff.css
        ///     * which is released under GNU General Public License v2
        ///     *
        ///     ** Diff rendering
        ///     */
        ///    table.diff {
        ///        font-size: &lt;&lt;&lt;FONT-SIZE&gt;&gt;&gt;px;
        ///        font-family: &lt;&lt;&lt;FONT-FAMILY&gt;&gt;&gt;;
        ///        background-color: white;
        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string diffStart {
            get {
                return ResourceManager.GetString("diffStart", resourceCulture);
            }
        }
    }
}
